name: Update packages

on:
  #schedule:
    #- cron: 0 */24 * * *
  watch:
    types: started
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  merge:
    runs-on: Ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        git clone -b main https://github.com/WangQi107/openwrt-package.git package
        cd package
        rm -rf *
        git rm --cache *
        git clone https://github.com/esirplayground/luci-app-poweroff.git ./luci-app-poweroff
        cd luci-app-poweroff
        rm -rf .git LICENSE README.md
        cd ../
        git clone https://github.com/sbwml/luci-app-alist.git ./alistcode
        cd alistcode
        mv alist ../
        mv luci-app-alist ../
        cd ../
        rm -rf alistcode
        git clone https://github.com/xiangfeidexiaohuo/openwrt-packages.git ./homeboxcode
        cd homeboxcode/op-homebox
        mv homebox ../../
        mv luci-app-homebox ../../
        cd ../../
        rm -rf homeboxcode
        git clone https://github.com/helmiau/helmiwrt-adds.git ./telegrambotcode
        cd telegrambotcode/packages/net
        mv telegrambot ../../../
        cd ../../luci
        mv luci-app-telegrambot ../../
        cd ../../
        rm -rf telegrambotcode
        git clone https://github.com/ZeaKyX/luci-app-speedtest-web.git ./luci-app-speedtest-web
        cd luci-app-speedtest-web
        rm -rf .git img LICENSE README.md
        cd ../
        git clone https://github.com/ZeaKyX/speedtest-web.git
        cd speedtest-web
        rm -rf .git LICENSE README.md
        cd ../../
        
    - name: Upload
      run: |
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/package
        cd $GITHUB_WORKSPACE/package
        git add .
        git commit -m "Auto Update $(TZ='Asia/Shanghai' date +%Y-%m-%d" "%H:%M:%S)"
        git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/WangQi107/openwrt-package.git"
