name: Update packages

on:
  schedule:
    - cron: 0 */24 * * *
  watch:
    types: started
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  merge:
    runs-on: Ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        git clone -b main https://github.com/WangQi107/openwrt-package.git package
        cd package
        rm -rf *
        git rm --cache *
        git clone https://github.com/esirplayground/luci-app-poweroff.git ./luci-app-poweroff
        cd luci-app-poweroff
        rm -rf .git LICENSE README.md
        cd ../
        git clone https://github.com/sbwml/luci-app-alist.git ./luci-app-alist
        cd luci-app-alist
        rm -rf .git .github README.md install.sh
        cd ../
        git clone https://github.com/xiangfeidexiaohuo/openwrt-packages.git ./homebox
        cd homebox
        mv op-homebox ../luci-app-homebox
        cd ../
        rm -rf homebox
        git clone https://github.com/helmiau/helmiwrt-adds.git ./luci-app-telegrambot
        cd luci-app-telegrambot
        rm -rf .git .github build-ipk .gitattributes .gitignore LICENSE README.md
        cd ../
        
    - name: Upload
      run: |
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/package
        cd $GITHUB_WORKSPACE/package
        git add .
        git commit -m "Auto Update $(TZ='Asia/Shanghai' date +%Y-%m-%d" "%H:%M:%S)"
        git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/WangQi107/openwrt-package.git"
